import Head from 'next/head'
import { useQuery } from 'hooks/useQuery'

export default function Home() {
  const test = useQuery('categories', '/api/test')
  return (
    <div>
      <Head>
        <title>Zwinne metodologie</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="bg-amber-500">
        <h1>Zwinne metodologie</h1>
        <p>domyślna strona startowa</p>
      </main>
    </div>
  )
}
